# FOLDER PATHS
TEMP_AUDIO_DIR = 'temp_audio_files'
TEMP_VIDEO_DIR = 'temp_video_files'
OUTPUT_DIR = '../output'

# COLORS
BACKGROUND_COLOR = (0, 0, 0)
TEXT_COLOR = (255, 255, 255)

# SIZES
HEIGHT = 720
WIDTH = 720
MAX_WIDTH = 600
FONT_SIZE = 60

# MEDIA
DURATION_BETWEEN_FRAGMENTS = 300 # ms
FPS = 24