import os

# FOLDER PATHS
TEMP_DIR = os.getcwd() + '/tmp'
OUTPUT_DIR = os.getcwd() + '/output'

# COLORS
BACKGROUND_COLOR = (0, 0, 0)
TEXT_COLOR = (255, 255, 255)

# SIZES
HEIGHT = 720
WIDTH = 720
MAX_WIDTH = 600
FONT_SIZE = 80

# MEDIA
DURATION_BETWEEN_FRAGMENTS = 0  # ms
FPS = 24
